---
- hosts: test
  become: yes
  tasks:

  - block:
    - name: update
      apt: update_cache=yes
      ignore_errors: yes

    - name: Installating JDK.
      apt: name=default-jdk state=latest

#    - name: Adding Group and user for Tomcat.
#      shell: groupadd tomcat && useradd -s /bin/false -g tomcat -d /opt/tomcat tomcat
    - name: Adding Group
      group:
        name: tomcat

    - name: Adding User for Tomcat.
      user:
        name: tomcat
        group: tomcat
        home: /opt/tomcat

    - name: Installating curl.
      apt: name=curl state=latest

    - name: Downloading Apache Tomcat tar.
      shell: wget https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.79/bin/apache-tomcat-8.5.79.tar.gz
      args:
        chdir: /tmp
#    - name: Creating Apache Tomcat home directory.
#      command: mkdir /opt/tomcat
    - name: Creating Apache Tomcat home directory.
      file:
        path: /opt/tomcat
        state: directory
        mode: '0755'

    - name: Extracting Apache Tomcat.
      shell: tar -xzvf /tmp/a