---
- block: ##### BLOCK FOR UBUNTU #####
  - name: Update packages.
    apt: update_cache=yes
    ignore_errors: yes

  - name: Installating JDK.
    apt: name=default-jdk state=latest

  - name: Adding Group and user for Tomcat.
    shell: groupadd tomcat && useradd -s /bin/false -g tomcat -d /opt/tomcat tomcat

  - name: Installating curl.
    apt: name=curl state=latest

  - name: Downloading Apache Tomcat tar.
    shell: wget {{ tomcat_archive }}
    args:
      chdir: /tmp
  - name: Creating Apache Tomcat home directory.
    command: mkdir /opt/tomcat

  - name: Extracting Apache Tomcat.
    shell: tar -xzvf /tmp/apache-tomcat-8*tar.gz -C /opt/tomcat --strip-components=1

  - name: Updating permission.
    command: "{{ item }}"
    with_items:
      - chown -R tomcat:tomcat /opt/tomcat
      - chmod -R g+r /opt/tomcat/conf
      - chmod g+x /opt/tomcat/conf

  - name: Creating service for Apache tomcat.
    file:
      path: /etc/systemd/system/tomcat.service
      state: touch
      mode: u+rwx,g-rwx,o-x

  - name: Download tomcat config
    get_url:
      url: "{{ tomcat_service_config_debian }}"
      dest: /etc/systemd/system/tomcat.service
    notify:
      - Daemon reload
      - Start Apache Tomcat service on Debian
  when: ansible_os_family == "Debian"

- block: ##### BLOCK FOR REDHAT #####
  - name: Installating JDK.
#    yum: name=java-17-openjdk state=latest
    shell: sudo amazon-linux-extras install -y java-openjdk11

  - name: Adding Group and user for Tomcat.
    shell: sudo useradd -m -U -d /opt/tomcat -s /bin/false tomcat

  - name: Downloading Apache Tomcat tar
    shell: wget {{ tomcat_archive }}
    args:
        chdir: /tmp

  - name: Extracting Apache Tomcat.
    shell: tar -xzvf /tmp/apache-tomcat-8*tar.gz

  - name: Making directory for Tomcat
    shell: mkdir -p /opt/tomcat

  - name: Mooving source files to Tomcat directory
    shell: mv apache-tomcat-8.5.79 /opt/tomcat/

  - name: Create a symbolic link
    shell: sudo ln -s /opt/tomcat/apache-tomcat-8.5.79 /opt/tomcat/latest

  - name: Change the directory ownership
    shell: sudo chown -R tomcat:tomcat /opt/tomcat

  - name: Make the scripts inside bin directory executable
    shell: sudo sh -c 'chmod +x /opt/tomcat/latest/bin/*.sh'

  - name: Create a systemd unit file
    shell: sudo wget {{ tomcat_service_config_redhat }}
    args:
        chdir: /etc/systemd/system/
    notify:
      - Daemon reload
      - Start Apache Tomcat service on RedHat
  when: ansible_os_family == "RedHat"
