---
- name: My Playbook for variables
  hosts: all
  become: yes


  vars:
    message1: Hello
    message2: World
    secret  : password

  tasks:
  
  - name: Print secret variable
    debug:
      var: secret

  - name: Print secret via debug msg
    debug:
      msg: "The password is: {{ secret }}"

  - debug:
      msg: "The owner of this server is {{ owner }}"

  - set_fact: full_message="{{ message1 }} {{ message2 }} from {{ owner }}"

  - debug:
      var: full_message

  - debug:
      var: ansible_distribution

  - shell: uptime
    register: results

  - debug:
      var: results.stdout
